---
# https://www.gitpod.io/docs
# https://www.gitpod.io/docs/references/gitpod-yml

# ------------------------------------------------------------------------------------------------------------------------------------------
# Commands to start on workspace startup
# Define how Gitpod prepares & builds your project and how it can start the project’s development server(s).
tasks:
  - name: Dependencies
    init: |
      cd ./fr-url-shortener
      cargo build
      psql -U '' postgres -c 'create database urlshortenerdb;' # Create the database
      task dbfullsetup # Run Diesel migrations and load initial data
      cd ..
#    command: |
#      cargo run

# ------------------------------------------------------------------------------------------------------------------------------------------
# Define a custom Docker image to be used for workspaces.
image:
  file: .gitpod.Dockerfile

# ------------------------------------------------------------------------------------------------------------------------------------------
# Define which path Gitpod considers the project’s workspace directory, relative to /workspace.
# workspaceLocation: "./fr-url-shortener"
# ------------------------------------------------------------------------------------------------------------------------------------------
# exposed ports
ports:
  - name: Web
    port: 8080
    onOpen: ignore
  - name: Database
    port: 5432
    onOpen: notify
    visibility: private

# ------------------------------------------------------------------------------------------------------------------------------------------
# Configure the VS Code editor. It uses https://open-vsx.org/
vscode:
  extensions:
#    - rust-lang.rust-analyzer
    - pinage404.rust-extension-pack

# ------------------------------------------------------------------------------------------------------------------------------------------
# Define the integration between Gitpod and JetBrains IDEs.

jetbrains:
  goland:
    vmoptions: "-Xms2048m -Xmx2048m -XX:ReservedCodeCacheSize=1024m -Didea.connection.timeout=3600000"
    # Find a page of the required plugin.
    # Select the Versions tab.
    # Click any version to copy the pluginId (short name such as org.rust.lang) of the plugin you want to install.
    plugins:
      - org.rust.lang # Rust
      - org.toml.lang # Toml
      - zielu.gittoolbox # GitToolBox
      - izhangzhihao.rainbow.brackets # Rainbow Brackets
      - lechuck.intellij-plugin.task # Taskfile
      - cn.yiiguxing.plugin.translate # Translation
      - com.intellij.grazie.pro # Grazie pro
      - de.endrullis.idea.postfixtemplates # Custom Postfix Templates
      - ru.adelf.idea.dotenv # .env files support
      - String Manipulation # String Manipulation
      - com.ultrahob.zerolength.plugin # Zero Width Characters locator
    prebuilds:
      version: stable
