# Task reference usage https://taskfile.dev/usage/
version: 3
env:
  APP_DATABASE_URL: postgresql://localhost:5432/urlshortenerdb

tasks:
  hello:
    cmds:
      - echo "Task works ok!!!"
  dbfullsetup:
    cmds:
      - task: dieselmigrationrun
      - task: loadinfo
      - echo "db setup finished"
  createdb:
    cmds:
      - psql -U '' postgres -c 'create database urlshortenerdb;'
  loadinfo:
    cmds:
      - psql -U '' -d urlshortenerdb -a -f "/workspace/rust-projects/fr-url-shortener/init_data.sql"
  dieselmigrationrun:
    cmds:
      - echo 'runing migration into' '<'$APP_DATABASE_URL'>'
      - diesel migration run --database-url $APP_DATABASE_URL
  echotest:
    cmds:
      - echo 'runing migration into' '<'$APP_DATABASE_URL'>'
