[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"
authors = ["Eduardo Flores"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0.3"